/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddButton: typeof import('./components/StandardButton.vue')['default']
    AddItemDialog: typeof import('./components/dialog/AddItemDialog.vue')['default']
    AddProductDialog: typeof import('./components/dialog/AddItemDialog.vue')['default']
    AddToListDialog: typeof import('./components/dialog/AddToListDialog.vue')['default']
    AddToPantryDialog: typeof import('./components/dialog/AddToPantryDialog.vue')['default']
    BaseDialog: typeof import('./components/dialog/BaseDialog.vue')['default']
    ConfirDeleteListDialog: typeof import('./components/dialog/ConfirmDeleteListDialog.vue')['default']
    ConfirmDeleteDialog: typeof import('./components/dialog/ConfirmDeleteDialog.vue')['default']
    ConfirmDeleteListDialog: typeof import('./components/dialog/ConfirmDeleteListDialog.vue')['default']
    copy: typeof import('./components/CreateListDialog copy.vue')['default']
    CreateCategoryDialog: typeof import('./components/dialog/CreateCategoryDialog.vue')['default']
    CreateListDialog: typeof import('./components/dialog/CreateListDialog.vue')['default']
    CreatePantryDialog: typeof import('./components/dialog/CreatePantryDialog.vue')['default']
    CreateProductDialog: typeof import('./components/dialog/CreateProductDialog.vue')['default']
    EditCategoryDialog: typeof import('./components/dialog/EditCategoryDialog.vue')['default']
    EditListDialog: typeof import('./components/dialog/EditListDialog.vue')['default']
    EditPantryDialog: typeof import('./components/dialog/EditPantryDialog.vue')['default']
    ExampleCustomDialog: typeof import('./components/ExampleCustomDialog.vue')['default']
    LinkButton: typeof import('./components/LinkButton.vue')['default']
    ListCard: typeof import('./components/List/ListCard.vue')['default']
    ListItemCard: typeof import('./components/List/ListItemCard.vue')['default']
    MoveToCategoryDialog: typeof import('./components/dialog/MoveToCategoryDialog.vue')['default']
    MoveToPantryDialog: typeof import('./components/dialog/MoveToPantryDialog.vue')['default']
    NavBar: typeof import('./components/layouts/NavBar.vue')['default']
    NavBarButton: typeof import('./components/NavBar/NavBarButton.vue')['default']
    NavBarTitle: typeof import('./components/NavBar/NavBarTitle.vue')['default']
    NavListItem: typeof import('./components/NavBar/NavListItem.vue')['default']
    PantryItemCard: typeof import('./components/Pantry/PantryItemCard.vue')['default']
    ProductCard: typeof import('./components/Products/ProductCard.vue')['default']
    ProductItemCard: typeof import('./components/Products/ProductItemCard.vue')['default']
    ProfilePanel: typeof import('./components/Profile/ProfilePanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    SettingRowAction: typeof import('./components/Settings/SettingRowAction.vue')['default']
    SettingRowActionSecondary: typeof import('./components/Settings/SettingRowActionSecondary.vue')['default']
    SettingRowToggle: typeof import('./components/Settings/SettingRowToggle.vue')['default']
    SettingsSectionCard: typeof import('./components/Settings/SettingsSectionCard.vue')['default']
    ShareListDialog: typeof import('./components/dialog/ShareListDialog.vue')['default']
    StandardButton: typeof import('./components/StandardButton.vue')['default']
    ToastContainer: typeof import('./components/ToastContainer.vue')['default']
    ToastNotification: typeof import('./components/ToastNotification.vue')['default']
  }
}
