/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddButton: typeof import('./components/StandardButton.vue')['default']
    CreateListDialog: typeof import('./components/CreateListDialog.vue')['default']
    ListCard: typeof import('./components/List/ListCard.vue')['default']
    ListItemCard: typeof import('./components/List/ListItemCard.vue')['default']
    NavBarButton: typeof import('./components/NavBar/NavBarButton.vue')['default']
    NavBarTitle: typeof import('./components/NavBar/NavBarTitle.vue')['default']
    NavListItem: typeof import('./components/NavBar/NavListItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    StandardButton: typeof import('./components/StandardButton.vue')['default']
  }
}
