/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddButton: typeof import('./components/StandardButton.vue')['default']
    AddToListDialog: typeof import('./components/AddToListDialog.vue')['default']
    copy: typeof import('./components/CreateListDialog copy.vue')['default']
    CreateCategoryDialog: typeof import('./components/CreateCategoryDialog.vue')['default']
    CreateListDialog: typeof import('./components/CreateListDialog.vue')['default']
    CreateProductDialog: typeof import('./components/CreateProductDialog.vue')['default']
    ListCard: typeof import('./components/List/ListCard.vue')['default']
    ListItemCard: typeof import('./components/List/ListItemCard.vue')['default']
    MoveToCategoryDialog: typeof import('./components/MoveToCategoryDialog.vue')['default']
    NavBarButton: typeof import('./components/NavBar/NavBarButton.vue')['default']
    NavBarTitle: typeof import('./components/NavBar/NavBarTitle.vue')['default']
    NavListItem: typeof import('./components/NavBar/NavListItem.vue')['default']
    ProductCard: typeof import('./components/Products/ProductCard.vue')['default']
    ProductItemCard: typeof import('./components/Products/ProductItemCard.vue')['default']
    ProfilePanel: typeof import('./components/Profile/ProfilePanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    SettingRowAction: typeof import('./components/Settings/SettingRowAction.vue')['default']
    SettingRowActionSecondary: typeof import('./components/Settings/SettingRowActionSecondary.vue')['default']
    SettingRowToggle: typeof import('./components/Settings/SettingRowToggle.vue')['default']
    SettingsSectionCard: typeof import('./components/Settings/SettingsSectionCard.vue')['default']
    StandardButton: typeof import('./components/StandardButton.vue')['default']
  }
}
